tasks:
  - init: |
      go install github.com/spf13/cobra-cli@latest
      go get github.com/spf13/cobra/cobra
      go build
    command: |
      ./azure-env --help
vscode:
  extensions:
    - golang.go
    - com.intellij.plugins.vscodekeymap
    - uk.co.ben-gibson.remote.repository.mapper